### ISSUE TITLE
No module named simple

### ISSUE THREAD

**Issue by beiliubei** [winkidney/weixin2py#4]
run sh runtestserver.sh

No module named simple
python 2.7
Django==1.8.2

http://stackoverflow.com/questions/11428427/no-module-named-simple-error-in-django

**Comment by winkidney** [comment]
Thanks for your issue!
I will check it and run it on django 1.8 for test!

**Comment by winkidney** [comment]
新建了个交流群416407192，可以加入，提到的问题已经解决，现在不在适配特定版本，因为1.7要求的testrunner已经不再需要，weixin2py包不受影响，只是demo里有需要1.7以前版本的这个语句。
没有问题的话我关闭issue了，有问题我可以重开。
