### ISSUE TITLE
提升会话状态的功能

### ISSUE THREAD

**Issue by zh-h** [winkidney/weixin2py#6]
我自己实现的一个会话只能保持一级菜单的功能，不能无限自由分级。此外我不会会用线程锁，只好用更简单的redis

**Comment by winkidney** [comment]
Hi,
你需要记录当前的会话层级状态：）用Session和Redis当然都可以做到。
线程锁在web应用里面使用是有问题的（因为web worker的进程和线程存在很多不确定性），所以使用redis更好

**Comment by winkidney** [comment]
No further comment, closed.
